---
all:
  children:
    attack_nodes:
      hosts:
        sapphros-attack:
          ansible_host: 192.168.1.19

    core_nodes:
      hosts:
        sapphros-core:
          ansible_host: 192.168.1.20

  vars:
    ansible_user: sapphros
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519_sapphros_lab
    ansible_python_interpreter: /usr/bin/python3
